### PR TITLE
Update React to 0.13.1

### PR DESCRIPTION
**Pull request by jantimon**
I updated the react library and patched the client and server to match the [react api changes](https://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#renamed-apis).

As the `react-addons` [npm package is deprecated](https://www.npmjs.com/package/react-addons) the `react-with-addons.js` file was build using browserify: 

``` bash
browserify --standalone React .npm/package/node_modules/react/addons.js > react-with-addons-0.13.1.js
```

It seems to work well in my project but I recommend further testing

### CODE REVIEW

**Comment by mystor** [comment]
Thanks for the PR. I'll try to find some time in the next couple of days to test out the changes, and I'll merge it when we get there.

**Comment by mystor** [comment]
I still don't have enough time to test it myself, can you confirm that the BlazeComponent still works correctly, and that reactive updates through meteor correctly trigger react re-renders?

**Comment by jantimon** [comment]
I haven't tested the BlazeComponents - However the (re)rendering works well

**Comment by Anonyfox** [comment]
I just used the `loginButtons` as BlazeComponent - works fine so far.  (https://atmospherejs.com/ian/accounts-ui-bootstrap-3)

**Comment by mystor** [comment]
I'm so sorry that I've been so busy, and unable to check up on this.

I imagine it probably is good, and will merge & publish it. Thank you so much @jantimon for the patch.

**Comment by mystor** [comment]
This has been merged & published. Hopefully there are no serious problems :)

**Comment by jantimon** [comment]
Cool :+1:

**Pull request merged**
